/**
 * Env-key name constants for the Gateway operator push configuration surface.
 *
 * Centralizing the key names here keeps `config.ts` and any future push
 * modules from drifting on the literal string values.
 */

export const OPERATOR_PUSH_ENABLED = 'GATEWAY_OPERATOR_PUSH_ENABLED'
export const OPERATOR_PUSH_VAPID_PUBLIC_KEY = 'GATEWAY_OPERATOR_PUSH_VAPID_PUBLIC_KEY'
export const OPERATOR_PUSH_VAPID_PRIVATE_KEY = 'GATEWAY_OPERATOR_PUSH_VAPID_PRIVATE_KEY'
export const OPERATOR_PUSH_VAPID_SUBJECT = 'GATEWAY_OPERATOR_PUSH_VAPID_SUBJECT'
export const OPERATOR_PUSH_VAPID_KEY_VERSION = 'GATEWAY_OPERATOR_PUSH_VAPID_KEY_VERSION'
export const OPERATOR_PUSH_PREVIOUS_VAPID_PUBLIC_KEY = 'GATEWAY_OPERATOR_PUSH_PREVIOUS_VAPID_PUBLIC_KEY'
export const OPERATOR_PUSH_PREVIOUS_VAPID_PRIVATE_KEY = 'GATEWAY_OPERATOR_PUSH_PREVIOUS_VAPID_PRIVATE_KEY'
export const OPERATOR_PUSH_PREVIOUS_VAPID_SUBJECT = 'GATEWAY_OPERATOR_PUSH_PREVIOUS_VAPID_SUBJECT'
export const OPERATOR_PUSH_PREVIOUS_VAPID_KEY_VERSION = 'GATEWAY_OPERATOR_PUSH_PREVIOUS_VAPID_KEY_VERSION'
export const OPERATOR_PUSH_DEDUPE_WINDOW_MS = 'GATEWAY_OPERATOR_PUSH_DEDUPE_WINDOW_MS'
