---
name: Setup Node.js and pnpm
description: Sets up pnpm package manager and Node.js with dependency caching

inputs:
  node-version:
    description: Node.js version to use. If not provided, reads from .node-version file.
    required: false
  install-dependencies:
    description: Whether to run pnpm bootstrap after setup
    required: false
    default: 'true'

outputs:
  node-version:
    description: The resolved Node.js version
    value: ${{ steps.setup-node.outputs.node-version }}

runs:
  using: composite
  steps:
    - name: 📦 Setup pnpm
      uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
      with:
        run_install: false

    - name: Setup Node.js
      id: setup-node
      uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
      with:
        cache: pnpm
        node-version: ${{ inputs.node-version }}
        node-version-file: ${{ inputs.node-version == '' && '.node-version' || '' }}

    - name: Install dependencies
      if: inputs.install-dependencies == 'true'
      shell: bash
      run: pnpm bootstrap
