---
config:
  MD013: false
  MD033:
    allowed_elements: [a, h3, img, p]
  MD041: false

globs:
  - '**/*.md'
  - '!node_modules'
  - '!.ai/**'
  - '!**/AGENTS.md'
  - '!PRD*.md'
  - '!FEATURES.md'
  - '!RULES.md'
  - '!RFCs/**'
  - '!RFCS.md'
