---
name: Fro Bot Agent
description: Template action (wait) for the Fro Bot Agent harness (WIP)
author: Fro Bot <agent@fro.bot>
inputs:
  milliseconds:
    required: true
    description: Time to wait (in milliseconds)
    default: '1000'
outputs:
  time:
    description: Current time (runner local time)
runs:
  using: node24
  main: dist/index.mjs
