---
name: Fro Bot Agent
description: AI agent with persistent memory for GitHub automation
author: Fro Bot <agent@fro.bot>

inputs:
  github-token:
    description: GitHub token (App installation token or PAT) with write permissions
    required: true
  auth-json:
    description: JSON object mapping provider IDs to auth configs
    required: true
  prompt:
    description: Custom prompt for the agent
    required: false
  session-retention:
    description: Number of sessions to retain (default 50)
    required: false
    default: '50'
  s3-backup:
    description: Enable S3 write-through backup
    required: false
    default: 'false'
  s3-bucket:
    description: S3 bucket for backup (required if s3-backup is true)
    required: false
  aws-region:
    description: AWS region for S3 bucket
    required: false

outputs:
  session-id:
    description: OpenCode session ID used for this run
  cache-status:
    description: Cache restore status (hit/miss/corrupted)
  duration:
    description: Run duration in seconds

runs:
  using: node24
  main: dist/main.js
