autoInstallPeers: true

ignoreWorkspaceRootCheck: true

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - unrs-resolver

overrides:
  brace-expansion: '>=5.0.5'
  fast-xml-parser: '>=5.5.7'
  flatted: 3.4.2
  handlebars: '>=4.7.9'
  picomatch: '>=4.0.4'
  tar@^7: '>=7.5.11'
  undici@^7: '>=7.24.0'
  yaml: '>=2.8.3'

savePrefix: ''

shamefullyHoist: true

shellEmulator: true

strictPeerDependencies: false
