#!/bin/sh
# Workspace executor entrypoint.
#
# Trusts the mitmproxy CA before launching the workspace-agent supervisor so
# that ALL outbound TLS clients in this container work through the egress proxy:
#   - git / libcurl (clone.ts)        — read the SYSTEM CA bundle
#   - opencode (Bun, --use-system-ca) — reads the SYSTEM CA bundle
#   - node fetch/https                — covered by NODE_EXTRA_CA_CERTS
#
# NODE_EXTRA_CA_CERTS alone is insufficient: git and opencode do not consult it.
# The CA must be installed into the system trust store via update-ca-certificates.
#
# The mitmproxy CA is generated by the sidecar at boot and mounted read-only at
# CA_SRC. In non-sandbox contexts (e.g. CI smoke with NO_PROXY=*), no CA is
# mounted; the script degrades sanely and still launches the supervisor.

set -eu

CA_SRC="${MITMPROXY_CA_PATH:-/run/mitmproxy-certs/mitmproxy-ca-cert.pem}"
CA_DEST="/usr/local/share/ca-certificates/mitmproxy.crt"
SYSTEM_BUNDLE="/etc/ssl/certs/ca-certificates.crt"
WAIT_SECONDS="${MITMPROXY_CA_WAIT_SECONDS:-30}"

install_ca() {
  # Wait for the mounted CA to appear (sidecar generates it on first boot).
  waited=0
  while [ ! -f "$CA_SRC" ]; do
    if [ "$waited" -ge "$WAIT_SECONDS" ]; then
      echo "workspace-entrypoint: no mitmproxy CA at $CA_SRC after ${WAIT_SECONDS}s — continuing without proxy trust" >&2
      return 1
    fi
    sleep 1
    waited=$((waited + 1))
  done

  cp "$CA_SRC" "$CA_DEST"
  # Regenerate the merged system bundle (base CAs + mitmproxy).
  update-ca-certificates >/dev/null 2>&1
  echo "workspace-entrypoint: installed mitmproxy CA into system trust store" >&2
  return 0
}

if install_ca; then
  # Point Node's fetch/https at the merged bundle too (belt-and-suspenders).
  export NODE_EXTRA_CA_CERTS="$SYSTEM_BUNDLE"
fi

# Hand off to the supervisor as PID 1 so its SIGTERM drain works.
exec node /app/apps/workspace-agent/dist/main.mjs
