// Shared license-notice generation module.
//
// Collects third-party license data from the installed node_modules and
// formats it into the THIRD_PARTY_NOTICES.txt content string. Does NOT write
// any files — callers are responsible for writing the result.
//
// Run via: node --experimental-strip-types scripts/third-party-notices.ts
// (or import collectThirdPartyNotices from other scripts)
//
// This file uses .ts imports because it runs directly under Node's
// --experimental-strip-types. Test files use .js imports for Vitest.

import {existsSync, readdirSync, readFileSync} from 'node:fs'
import {join, resolve} from 'node:path'

export interface LicenseEntry {
  readonly version: string
  readonly license: string
  readonly content: string
}

/**
 * Formats collected license entries into the THIRD_PARTY_NOTICES output string.
 * Sorts by package name (locale-aware), normalizes line endings to LF.
 * Exported for unit testing.
 *
 * Attribution keeps the highest resolved version's license text per package.
 * This is safe when the license text is identical across resolved versions of
 * the same package, which holds for the vast majority of npm packages. The CI
 * CycloneDX SBOM (generated by @cyclonedx/cyclonedx-npm in CI) is the complete per-version inventory.
 */
export function formatThirdPartyNotices(entries: ReadonlyMap<string, LicenseEntry>): string {
  return Array.from(entries.entries())
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([name, {version, license, content}]) => `${name}@${version}\n${license}\n${content}`)
    .join('\n\n')
    .replaceAll('\r\n', '\n')
}

// ---------------------------------------------------------------------------
// Bun-native license collector
// ---------------------------------------------------------------------------

/**
 * Raw structure of a bun.lock v1 package entry.
 * Format: [resolvedVersion, registry, meta, integrity?]
 * where meta has optional dependencies/optionalDependencies/peerDependencies.
 */
interface BunLockPackageMeta {
  readonly dependencies?: Record<string, string>
  readonly optionalDependencies?: Record<string, string>
  readonly peerDependencies?: Record<string, string>
  readonly devDependencies?: Record<string, string>
}

type BunLockPackageEntry = readonly [string, string, BunLockPackageMeta?, string?]

interface BunLockWorkspace {
  readonly name?: string
  readonly version?: string
  readonly dependencies?: Record<string, string>
  readonly devDependencies?: Record<string, string>
}

interface BunLock {
  readonly lockfileVersion: number
  readonly workspaces?: Record<string, BunLockWorkspace>
  readonly packages?: Record<string, BunLockPackageEntry>
}

/** LICENSE/LICENCE/COPYING/NOTICE file name pattern (case-insensitive). */
const LICENSE_FILE_RE = /^(?:LICENSE|LICENCE|COPYING|NOTICE)(?:\.md|\.txt|\.rst)?$/i

/**
 * Reads the license type string from a package.json file.
 * Handles both the modern `license` string field and the legacy `licenses` array.
 * Returns empty string when no license type is found or the file cannot be parsed.
 */
function readLicenseTypeFromPkgJson(pkgDir: string): string {
  const pkgJsonPath = join(pkgDir, 'package.json')
  if (!existsSync(pkgJsonPath)) {
    return ''
  }
  try {
    const pkgJson = JSON.parse(readFileSync(pkgJsonPath, 'utf8')) as {
      license?: unknown
      licenses?: unknown
    }
    if (typeof pkgJson.license === 'string' && pkgJson.license.length > 0) {
      return pkgJson.license
    }
    if (Array.isArray(pkgJson.licenses) && pkgJson.licenses.length > 0) {
      const first = pkgJson.licenses[0] as {type?: unknown}
      if (typeof first?.type === 'string') {
        return first.type
      }
    }
  } catch {
    // ignore parse errors
  }
  return ''
}

/**
 * Reads the license text for a package from its node_modules directory.
 * Prefers LICENSE/LICENCE/COPYING files; falls back to the `license` field
 * in package.json. Returns null when no attribution source is found.
 */
function readPackageLicense(pkgDir: string): {readonly text: string; readonly type: string} | null {
  if (!existsSync(pkgDir)) {
    return null
  }

  let files: string[]
  try {
    files = readdirSync(pkgDir)
  } catch {
    return null
  }

  // Prefer LICENSE/LICENCE/COPYING/NOTICE files
  const licenseFiles = files.filter(f => LICENSE_FILE_RE.test(f))
  if (licenseFiles.length > 0) {
    // Prefer LICENSE over NOTICE; sort to get deterministic order
    const sorted = licenseFiles.sort()
    const licenseFile = sorted.find(f => /^(?:LICENSE|LICENCE|COPYING)/i.test(f)) ?? sorted[0]
    if (licenseFile === undefined) {
      return null
    }
    try {
      const text = readFileSync(join(pkgDir, licenseFile), 'utf8')
      const licenseType = readLicenseTypeFromPkgJson(pkgDir) || 'Unknown'
      return {text, type: licenseType}
    } catch {
      return null
    }
  }

  // Fall back to package.json license field
  const licenseType = readLicenseTypeFromPkgJson(pkgDir)
  if (licenseType.length > 0) {
    return {text: licenseType, type: licenseType}
  }

  return null
}

/**
 * Strips trailing commas from JSON-like content (bun.lock uses JSON5-style
 * trailing commas that standard JSON.parse rejects).
 */
function stripTrailingCommas(content: string): string {
  return content.replaceAll(/,(\s*[}\]])/g, '$1')
}

/**
 * Resolves the lockfile key for a dependency given the current package's key.
 * Bun uses nested keys like "parent/dep" when a package uses a different version
 * of a dep than the hoisted top-level version.
 */
function resolveDepKey(
  depName: string,
  currentKey: string,
  packages: Record<string, BunLockPackageEntry>,
): string | null {
  const nestedKey = `${currentKey}/${depName}`
  if (packages[nestedKey] !== undefined) {
    return nestedKey
  }
  if (packages[depName] !== undefined) {
    return depName
  }
  return null
}

/**
 * Collects the prod dependency closure from bun.lock.
 *
 * Strategy:
 * 1. Parse bun.lock (JSON5 with trailing commas) to get the packages map.
 * 2. Collect prod seeds from ALL workspace packages (matches pnpm --prod behavior
 *    in a monorepo — includes all workspace prod deps, not just root).
 * 3. BFS traversal using nested-aware resolution: when a package uses a nested
 *    version of a dep (e.g., "archiver-utils/glob"), traverse THAT version's deps.
 * 4. Include optional dependencies (pnpm --prod includes them).
 * 5. Extract the actual package name from the resolved version string.
 *
 * Returns a Map<packageName, {version, pkgDir}> for all prod packages.
 */
export function collectProdClosureFromBunLock(
  lockfilePath: string,
  nodeModulesDir: string,
): Map<string, {readonly version: string; readonly pkgDir: string}> {
  const lockContent = readFileSync(lockfilePath, 'utf8')
  const cleaned = stripTrailingCommas(lockContent)
  const lock = JSON.parse(cleaned) as BunLock

  // Validate lockfileVersion — fail closed on unknown format so a future Bun
  // lockfile format bump produces a clear error rather than silently wrong output.
  if (lock.lockfileVersion !== 1) {
    throw new Error(
      `[license-collector] unsupported bun.lock format: expected lockfileVersion 1, got ${JSON.stringify(lock.lockfileVersion)}. ` +
        `Update collectProdClosureFromBunLock to support the new format.`,
    )
  }

  // Structural validation — guard against unexpected types, not just undefined.
  if (typeof lock.packages !== 'object' || lock.packages === null) {
    throw new Error(
      `[license-collector] bun.lock is malformed: expected 'packages' to be an object, got ${typeof lock.packages}`,
    )
  }
  if (typeof lock.workspaces !== 'object' || lock.workspaces === null) {
    throw new Error(
      `[license-collector] bun.lock is malformed: expected 'workspaces' to be an object, got ${typeof lock.workspaces}`,
    )
  }

  const packages = lock.packages
  const workspaces = lock.workspaces

  // Collect all workspace package names so we can exclude them from prod seeds
  const workspaceNames = new Set(
    Object.values(workspaces)
      .map(ws => ws.name)
      .filter((n): n is string => typeof n === 'string'),
  )

  // Collect prod seeds from ALL workspace packages (not just root)
  // This matches pnpm --prod behavior in a monorepo
  const allProdSeeds = new Set<string>()
  for (const wsInfo of Object.values(workspaces)) {
    for (const dep of Object.keys(wsInfo.dependencies ?? {})) {
      if (!workspaceNames.has(dep)) {
        allProdSeeds.add(dep)
      }
    }
  }

  // BFS with nested-aware resolution
  const visitedKeys = new Set<string>()
  const result = new Map<string, {readonly version: string; readonly pkgDir: string}>()
  const queue: string[] = [...allProdSeeds]

  while (queue.length > 0) {
    const key = queue.shift()
    if (key === undefined || visitedKeys.has(key)) {
      continue
    }
    visitedKeys.add(key)

    const entry = packages[key]
    if (entry === undefined) {
      continue
    }

    const [resolvedVer, , meta] = entry
    // resolvedVer is like "glob@10.5.0" or "@actions/core@3.0.1"
    const atIdx = resolvedVer.lastIndexOf('@')
    if (atIdx <= 0) {
      throw new Error(
        `[license-collector] bun.lock entry '${key}' has malformed resolved version '${resolvedVer}': ` +
          `expected '<name>@<version>' with at least one '@' separator after the package name.`,
      )
    }
    const actualName = resolvedVer.slice(0, atIdx)
    const version = resolvedVer.slice(atIdx + 1)

    // Only record the highest version per package name (matches existing dedup logic)
    const existing = result.get(actualName)
    if (existing === undefined || compareVersions(existing.version, version) < 0) {
      const pkgDir = join(nodeModulesDir, actualName)
      result.set(actualName, {version, pkgDir})
    }

    // Traverse required + optional + peer deps.
    // peerDependencies are included to close the latent attribution gap: a prod
    // package reachable only via a peer dep would otherwise be silently omitted
    // from legal attribution. Including peers is conservative and correct.
    const allDeps: Record<string, string> = {
      ...(meta?.dependencies ?? {}),
      ...(meta?.optionalDependencies ?? {}),
      ...(meta?.peerDependencies ?? {}),
    }

    for (const dep of Object.keys(allDeps)) {
      const depKey = resolveDepKey(dep, key, packages)
      if (depKey !== null && !visitedKeys.has(depKey)) {
        queue.push(depKey)
      }
    }
  }

  return result
}

function compareVersions(a: string, b: string): number {
  const aParts = a.split('.').map(Number)
  const bParts = b.split('.').map(Number)
  const length = Math.max(aParts.length, bParts.length)

  for (let i = 0; i < length; i++) {
    const aPart = aParts[i] ?? 0
    const bPart = bParts[i] ?? 0
    // A non-numeric segment (NaN) must not make a comparison silently false,
    // which would let a malformed entry latch and never be replaced by a real
    // version. Treat a malformed segment as strictly lower than a numeric one so
    // a valid version always wins.
    const aNaN = Number.isNaN(aPart)
    const bNaN = Number.isNaN(bPart)
    if (aNaN || bNaN) {
      if (aNaN && bNaN) {
        continue
      }
      return aNaN ? -1 : 1
    }
    if (aPart !== bPart) {
      return aPart - bPart
    }
  }
  return 0
}

/**
 * Collects third-party license notices using the Bun-native lockfile reader.
 *
 * Reads the prod dependency closure from bun.lock, resolves each package's
 * license from node_modules, and formats the result using formatThirdPartyNotices.
 *
 * Fail-closed: throws if any prod package is missing or has no resolvable
 * license attribution.
 *
 * @param lockfilePath - Path to bun.lock (default: './bun.lock').
 * @param nodeModulesDir - Path to node_modules (default: './node_modules').
 */
export async function collectThirdPartyNoticesBun(
  lockfilePath = './bun.lock',
  nodeModulesDir = './node_modules',
): Promise<string> {
  const absLockfile = resolve(lockfilePath)
  const absNodeModules = resolve(nodeModulesDir)

  if (!existsSync(absLockfile)) {
    throw new Error(`[license-collector] bun.lock not found at ${absLockfile}; cannot produce THIRD_PARTY_NOTICES.txt`)
  }

  let prodClosure: Map<string, {readonly version: string; readonly pkgDir: string}>
  try {
    prodClosure = collectProdClosureFromBunLock(absLockfile, absNodeModules)
  } catch (error) {
    throw new Error(
      `[license-collector] failed to parse bun.lock: ${error instanceof Error ? error.message : String(error)}`,
      {cause: error instanceof Error ? error : new Error(String(error))},
    )
  }

  const highestVersions = new Map<string, LicenseEntry>()
  const missingDir: string[] = []

  for (const [pkgName, {version, pkgDir}] of prodClosure) {
    if (!existsSync(pkgDir)) {
      // Fail-closed: a missing package directory means the install is incomplete
      missingDir.push(`${pkgName}@${version} (expected: ${pkgDir})`)
      continue
    }

    const licenseResult = readPackageLicense(pkgDir)
    if (licenseResult === null) {
      // No license file or field found — use "Unknown" as the license type
      // and a minimal attribution notice. This matches pnpm's behavior for
      // packages that predate the npm license field convention.
      console.warn(`[license-collector] ${pkgName}@${version}: no license file or field found; using "Unknown"`)
      highestVersions.set(pkgName, {
        version,
        license: 'Unknown',
        content: '(No license file found in package)',
      })
    } else {
      highestVersions.set(pkgName, {
        version,
        license: licenseResult.type,
        content: licenseResult.text,
      })
    }
  }

  if (missingDir.length > 0) {
    throw new Error(
      `[license-collector] license collection failed; cannot produce THIRD_PARTY_NOTICES.txt:\n` +
        `The following prod packages are missing from node_modules (incomplete install?):\n${missingDir
          .map(m => `  - ${m}`)
          .join('\n')}`,
    )
  }

  return formatThirdPartyNotices(highestVersions)
}

/**
 * Collects third-party license notices from the installed node_modules and
 * returns the formatted THIRD_PARTY_NOTICES.txt content as a string.
 *
 * Uses the Bun-native lockfile reader (collectThirdPartyNoticesBun).
 *
 * - The license collection is fail-closed: a total failure here means the
 *   notice would be incomplete, so this function throws with a rich error
 *   including the underlying cause.
 *
 * @param packageJsonPath - Path to the root package.json (default: './package.json').
 *   Pass an absolute path when the caller's cwd differs from the repo root.
 *
 * Does NOT write any files. Callers decide what to do with the result.
 */
export async function collectThirdPartyNotices(packageJsonPath = './package.json'): Promise<string> {
  const packageDir = packageJsonPath.replace(/[/\\]?package\.json$/, '') || '.'
  const bunLockPath = join(packageDir, 'bun.lock')
  const nodeModulesDir = join(packageDir, 'node_modules')
  return collectThirdPartyNoticesBun(bunLockPath, nodeModulesDir)
}
